# Generated by Django 3.1.7 on 2021-04-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
